const vacations = [
    {
        vacationId: 0, image: "../../images/example.png", destination: "Brazil1", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 1, image: "../../images/example.png", destination: "Brazil2", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 2, image: "../../images/example.png", destination: "Brazil3", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 3, image: "../../images/example.png", destination: "Brazil4", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 4, image: "../../images/example.png", destination: "Brazil", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 5, image: "../../images/example.png", destination: "Brazil", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 6, image: "../../images/example.png", destination: "Brazil", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 7, image: "../../images/example.png", destination: "Brazil", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
},
    {
        vacationId: 8, image: "../../images/example.png", destination: "Brazil", price: 100, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tristique dolor a egestas interdum. Phasellus in felis id ipsum porttitor auctor sed ut quam. Cras ut augue non eros eleifend fringilla. Integer gravida sodales enim, at gravida nisl efficitur sed. Donec consectetur metus lectus, id vehicula nulla sagittis sed. Morbi facilisis quam metus, euismod tristique lorem vestibulum non. Curabitur ut malesuada dui. Cras facilisis dictum erat a imperdiet. Fusce luctus, dolor id aliquam pretium, leo justo commodo nisl, nec blandit metus erat eu mi. Nunc lacinia, turpis quis mattis malesuada, dolor justo tempor dolor, eget molestie libero tortor eu ex. Praesent pharetra sapien vitae neque iaculis, sed eleifend nibh fringilla. Suspendisse pellentesque ipsum at augue varius, nec iaculis arcu condimentum.", startDate: "2.9.2020", endDate:"11.11.2020", isFollowed: false
}
   
];

module.exports = vacations;